version: '3'

volumes:
  node_modules:

services:
  dartsense-site:
    build: .
    container_name: dartsense-site
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
